Chapter-07/website/src/project/apps/admin_honeypot/urls.py
from project.apps.admin_honeypot import views
from django.urls import path, re_path

app_name = "admin_honeypot"

urlpatterns = [
    path("login/", views.AdminHoneypot.as_view(), name="login"),
    re_path(r"^.*$", views.AdminHoneypot.as_view(), name="index"),
]

Chapter-07/website/src/project/apps/ideas/urls.py
from django.urls import path

# ============================================================================ #
from .views import (
    IdeaList,
    IdeaDetail,
    add_or_change_idea,
    delete_idea,
    idea_list,
    IdeaListView,
    idea_handout_pdf,
    download_idea_picture,
    idea_detail,
)

# ============================================================================ #


urlpatterns = [
    path("", idea_list, name="idea_list"),
    path("<uuid:pk>/", idea_detail, name="idea_detail"),
    # path("", IdeaListView.as_view(), name="idea_list"),
    path("add/", add_or_change_idea, name="add_idea"),
    # path("<uuid:pk>/", IdeaDetail.as_view(), name="idea_detail"),
    path("<uuid:pk>/change/", add_or_change_idea, name="change_idea"),
    path("<uuid:pk>/delete/", delete_idea, name="delete_idea"),
    path("<uuid:pk>/handout/", idea_handout_pdf, name="idea_handout"),
    path(
        "<uuid:pk>/download-picture/",
        download_idea_picture,
        name="download_idea_picture",
    ),
]

Chapter-07/website/src/project/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

from project.apps.external_auth import views

urlpatterns = i18n_patterns(
    # path("", lambda request: redirect("ideas:idea_list")),
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout, name="auth0_logout"),
    path("", include("social_django.urls")), 
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "admin/",
        include("project.apps.admin_honeypot.urls", namespace="admin_honeypot_fix"),
    ),
    path("secret/", admin.site.urls),
    path("ideas/", include(("project.apps.ideas.urls", "ideas"), namespace="ideas")),
    # path("search/", include("haystack.urls")),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT)

Chapter-07/website/src/project/apps/admin_honeypot/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from project.apps.admin_honeypot import listeners


class LoginAttempt(models.Model):
    username = models.CharField(_("username"), max_length=255, blank=True, null=True)
    ip_address = models.GenericIPAddressField(
        _("ip address"), protocol="both", blank=True, null=True
    )
    session_key = models.CharField(
        _("session key"), max_length=50, blank=True, null=True
    )
    user_agent = models.TextField(_("user-agent"), blank=True, null=True)
    timestamp = models.DateTimeField(_("timestamp"), auto_now_add=True)
    path = models.TextField(_("path"), blank=True, null=True)

    class Meta:
        verbose_name = _("login attempt")
        verbose_name_plural = _("login attempts")
        ordering = ("timestamp",)

    def __str__(self):
        return self.username

Chapter-07/website/src/project/apps/categories/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from project.apps.core.model_fields import TranslatedField


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=200)

    translated_title = TranslatedField("title")

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.title


class CategoryTranslations(models.Model):
    category = models.ForeignKey(
        Category,
        verbose_name=_("Category"),
        on_delete=models.CASCADE,
        related_name="translations",
    )
    language = models.CharField(_("Language"), max_length=7)

    title = models.CharField(_("Title"), max_length=200)

    class Meta:
        verbose_name = _("Category Translations")
        verbose_name_plural = _("Category Translations")
        ordering = ["language"]
        unique_together = [["category", "language"]]

    def __str__(self):
        return self.title

Chapter-07/website/src/project/apps/viral_videos/models.py
from django.db import models

# Create your models here.

Chapter-07/website/src/project/apps/admin_honeypot/forms.py
from django import forms
from django.contrib.admin.forms import AdminAuthenticationForm


class HoneypotLoginForm(AdminAuthenticationForm):
    def clean(self):
        """
        Always raise the default error message, because we don't
        care what they entered here.
        """
        raise forms.ValidationError(
            self.error_messages["invalid_login"],
            code="invalid_login",
            params={"username": self.username_field.verbose_name},
        )

Chapter-07/website/src/project/apps/admin_honeypot/views.py
import django

from ipware import get_client_ip

from project.apps.admin_honeypot.forms import HoneypotLoginForm
from project.apps.admin_honeypot.models import LoginAttempt
from project.apps.admin_honeypot.signals import honeypot

from django.contrib.admin.sites import AdminSite
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.views import redirect_to_login
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import generic


class AdminHoneypot(generic.FormView):
    template_name = "admin_honeypot/login.html"
    form_class = HoneypotLoginForm

    def dispatch(self, request, *args, **kwargs):
        if not request.path.endswith("/"):
            return redirect(request.path + "/", permanent=True)

        # Django redirects the user to an explicit login view with
        # a next parameter, so emulate that.
        login_url = reverse("admin_honeypot:login")
        if request.path != login_url:
            return redirect_to_login(request.get_full_path(), login_url)

        return super(AdminHoneypot, self).dispatch(request, *args, **kwargs)

    def get_form(self, form_class=form_class):
        return form_class(self.request, **self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        context = super(AdminHoneypot, self).get_context_data(**kwargs)
        context.update(
            {
                **AdminSite().each_context(self.request),
                "app_path": self.request.get_full_path(),
                REDIRECT_FIELD_NAME: reverse("admin_honeypot:index"),
                "title": _("Log in"),
            }
        )
        return context

    def form_valid(self, form):
        return self.form_invalid(form)

    def form_invalid(self, form):
        ip_address, is_routable = get_client_ip(self.request)
        instance = LoginAttempt.objects.create(
            username=self.request.POST.get("username"),
            session_key=self.request.session.session_key,
            ip_address=ip_address,
            user_agent=self.request.META.get("HTTP_USER_AGENT"),
            path=self.request.get_full_path(),
        )
        honeypot.send(sender=LoginAttempt, instance=instance, request=self.request)
        return super(AdminHoneypot, self).form_invalid(form)

Chapter-07/website/src/project/apps/categories/views.py
from django.shortcuts import render

# Create your views here.

Chapter-07/website/src/project/apps/external_auth/views.py
from urllib.parse import urlencode

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as log_out
from django.conf import settings



def index(request):
    user = request.user
    if user.is_authenticated:
        return redirect(dashboard)
    else:
        return render(request, "index.html")


@login_required
def dashboard(request):
    return render(request, "dashboard.html")


def logout(request):
    log_out(request)
    return_to = urlencode({"returnTo": request.build_absolute_uri("/")})
    logout_url = "https://%s/v2/logout?client_id=%s&%s" % (
        settings.SOCIAL_AUTH_AUTH0_DOMAIN,
        settings.SOCIAL_AUTH_AUTH0_KEY,
        return_to,
    )
    return redirect(logout_url)

Chapter-07/website/src/project/apps/ideas/views.py
from weasyprint import HTML
from weasyprint.text.fonts import FontConfiguration
import os

# ============================================================================ #
from django.template.loader import render_to_string
from django.utils.timezone import now as timezone_now
from django.utils.text import slugify
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.forms import modelformset_factory
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views.generic import View
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.http import FileResponse, HttpResponseNotFound

# ============================================================================ #
from .forms import IdeaForm, IdeaTranslationsForm
from .models import Idea, IdeaTranslations
from .forms import IdeaFilterForm
from .models import Idea, RATING_CHOICES

# ============================================================================ #
PAGE_SIZE = getattr(settings, "PAGE_SIZE", 24)


@login_required
def download_idea_picture(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    if idea.picture:
        filename, extension = os.path.splitext(idea.picture.file.name)
        extension = extension[1:]  # remove the dot
        response = FileResponse(idea.picture.file, content_type=f"image/{extension}")
        slug = slugify(idea.title)[:100]
        response["Content-Disposition"] = "attachment; filename=" f"{slug}.{extension}"
    else:
        response = HttpResponseNotFound(content="Picture unavailable")
    return response


# =============================== GENERATE PDF =============================== #


def idea_handout_pdf(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    context = {"idea": idea}
    html = render_to_string("ideas/idea_handout_pdf.html", context)

    response = HttpResponse(content_type="application/pdf")
    response[
        "Content-Disposition"
    ] = "inline; filename={date}-{name}-handout.pdf".format(
        date=timezone_now().strftime("%Y-%m-%d"), name=slugify(idea.translated_title)
    )

    font_config = FontConfiguration()
    HTML(string=html).write_pdf(response, font_config=font_config)

    return response


# ================================= IDEA LIST ================================ #


def idea_list(request):
    qs = Idea.objects.order_by("title")
    form = IdeaFilterForm(data=request.GET)
    facets = {
        "selected": {},
        "categories": {
            "authors": form.fields["author"].queryset,
            "categories": form.fields["category"].queryset,
            "ratings": RATING_CHOICES,
        },
    }

    if form.is_valid():
        filters = (
            ("author", "author"),
            ("category", "categories"),
            ("rating", "rating"),
        )
        qs = filter_facets(facets, qs, form, filters)

    paginator = Paginator(qs, PAGE_SIZE)
    page_number = request.GET.get("page")
    try:
        page = paginator.page(page_number)
    except PageNotAnInteger:

        page = paginator.page(1)
    except EmptyPage:

        page = paginator.page(paginator.num_pages)

    context = {
        "form": form,
        "facets": facets,
        "object_list": page,
    }
    return render(request, "ideas/idea_list.html", context)


# =============================== FILTER FACETS ============================== #


def filter_facets(facets, qs, form, filters):
    for query_param, filter_param in filters:
        value = form.cleaned_data[query_param]
        if value:
            selected_value = value
            if query_param == "rating":
                rating = int(value)
                selected_value = (rating, dict(RATING_CHOICES)[rating])
            facets["selected"][query_param] = selected_value
            filter_args = {filter_param: value}
            qs = qs.filter(**filter_args).distinct()
    return qs


# ============================== IDEA LIST VIEW ============================== #
class IdeaListView(View):
    form_class = IdeaFilterForm
    template_name = "ideas/idea_list.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(data=request.GET)
        qs, facets = self.get_queryset_and_facets(form)
        page = self.get_page(request, qs)
        context = {"form": form, "facets": facets, "object_list": page}
        return render(request, self.template_name, context)

    def get_queryset_and_facets(self, form):
        qs = Idea.objects.order_by("title")
        facets = {
            "selected": {},
            "categories": {
                "authors": form.fields["author"].queryset,
                "categories": form.fields["category"].queryset,
                "ratings": RATING_CHOICES,
            },
        }

        if form.is_valid():
            filters = (
                ("author", "author"),
                ("category", "categories"),
                ("rating", "rating"),
            )
            qs = self.filter_facets(facets, qs, form, filters)
        return qs, facets

    @staticmethod
    def filter_facets(facets, qs, form, filters):
        for query_param, filter_param in filters:
            value = form.cleaned_data[query_param]
            if value:
                selected_value = value
                if query_param == "rating":
                    rating = int(value)
                    selected_value = (rating, dict(RATING_CHOICES)[rating])
                    facets["selected"][query_param] = selected_value
                    filter_args = {filter_param: value}
                    qs = qs.filter(**filter_args).distinct()
            return qs

    def get_page(self, request, qs):
        paginator = Paginator(qs, PAGE_SIZE)
        page_number = request.GET.get("page")
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        return page


class IdeaList(ListView):
    model = Idea


class IdeaDetail(DetailView):
    model = Idea
    context_object_name = "idea"


def idea_detail(request, pk):
    idea = get_object_or_404(Idea, pk=pk)

    print("TESTTT", idea.picture.url)
    print("TESTTT 22", idea.picture_large.url)
    # print("TESTTT 33", idea.watermarked_picture_large.path)
    print("TESTTT 33", settings.STATIC_ROOT, "/site/img/watermark.png")

    context = {"idea": idea}

    return render(request, "ideas/idea_detail.html", context)


# =============================== CRUD FOR IDEA ============================== #


@login_required
def add_or_change_idea(request, pk=None):
    idea = None
    if pk:
        idea = get_object_or_404(Idea, pk=pk)
    IdeaTranslationsFormSet = modelformset_factory(
        IdeaTranslations, form=IdeaTranslationsForm, extra=0, can_delete=True
    )
    if request.method == "POST":
        print("STEP 1", request)
        form = IdeaForm(request, data=request.POST, files=request.FILES, instance=idea)
        translations_formset = IdeaTranslationsFormSet(
            queryset=IdeaTranslations.objects.filter(idea=idea),
            data=request.POST,
            files=request.FILES,
            prefix="translations",
            form_kwargs={"request": request},
        )
        if form.is_valid() and translations_formset.is_valid():
            idea = form.save()
            translations = translations_formset.save(commit=False)
            for translation in translations:
                translation.idea = idea
                translation.save()
            translations_formset.save_m2m()
            for translation in translations_formset.deleted_objects:
                translation.delete()
            return redirect("ideas:idea_detail", pk=idea.pk)
    else:
        print("STEP 2", request)
        form = IdeaForm(request, instance=idea)
        print("STEP 2", form)
        translations_formset = IdeaTranslationsFormSet(
            queryset=IdeaTranslations.objects.filter(idea=idea),
            prefix="translations",
            form_kwargs={"request": request},
        )

    context = {"idea": idea, "form": form, "translations_formset": translations_formset}
    return render(request, "ideas/idea_form.html", context)


@login_required
def delete_idea(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    # if request.method == "POST":
    idea.delete()
    return redirect("ideas:idea_list")
    # context = {"idea": idea}
    # return render(request, "ideas/idea_deleting_confirmation.html", context)

Chapter-07/website/src/project/apps/magazine/views.py
from django.shortcuts import render

# Create your views here.

Chapter-07/website/src/project/apps/viral_videos/views.py
from django.shortcuts import render

# Create your views here.

Chapter-07/website/src/project/templates/ideas/idea_deleting_confirmation.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Successful 🗑️🗑️🗑️</h1>
    <a href="/en/">Home</a>
  </body>
</html>

Chapter-07/website/src/project/templates/ideas/idea_detail.html
{% extends "base.html" %}
{% load i18n json_ld %}

{% block meta_tags %}
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ WEBSITE_URL }}{{ request.path }}" />
    <meta property="og:title" content="{{ idea.translated_title }}" />
    {% if idea.picture_social %}
        <meta property="og:image" content="{{ idea.picture_social.url }}" />
        <!-- Next tags are optional but recommended -->
        <meta property="og:image:width" content="{{ idea.picture_social.width }}" />
        <meta property="og:image:height" content="{{ idea.picture_social.height }}" />
    {% endif %}
    <meta property="og:description" content="{{ idea.translated_content }}" />
    <meta property="og:site_name" content="MyProject" />
    <meta property="og:locale" content="{{ LANGUAGE_CODE }}" />

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@DjangoTricks">
    <meta name="twitter:creator" content="@archatas">
    <meta name="twitter:url" content="{{ WEBSITE_URL }}{{ request.path }}">
    <meta name="twitter:title" content="{{ idea.translated_title }}">
    <meta name="twitter:description" content="{{ idea.translated_content }}">
    {% if idea.picture_social %}
        <meta name="twitter:image" content="{{ idea.picture_social.url }}">
    {% endif %}

    {% render_json_ld idea.structured_data %}
{% endblock %}


{% block content %}
    <a href="{% url "ideas:idea_list" %}">{% trans "List of ideas" %}</a>
    <h1>
        {% blocktrans trimmed with title=idea.translated_title %}
            Idea "{{ title }}"
        {% endblocktrans %}
    </h1>
     <img src="{{ idea.watermarked_picture_large.url }}" alt="" />
    {{ idea.translated_content|linebreaks|urlize }}
    <p>
        {% for category in idea.categories.all %}
            <span class="badge badge-pill badge-info">{{ category.translated_title }}</span>
        {% endfor %}
    </p>
    <a href="{% url 'ideas:download_idea_picture' pk=idea.pk %}" class="btn btn-primary">{% trans "Download picture" %}</a>
    <a href="{% url 'ideas:idea_handout' pk=idea.pk %}" class="btn btn-primary">{% trans "Download handout" %}</a>
    <a href="{% url 'ideas:change_idea' pk=idea.pk %}" class="btn btn-primary">{% trans "Change this idea" %}</a>
    <a href="{% url 'ideas:delete_idea' pk=idea.pk %}" class="btn btn-danger">{% trans "Delete this idea" %}</a>
{% endblock %}

Chapter-07/website/src/project/templates/ideas/idea_form.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags static %}
 

{% block content %}
    <a href="{% url "ideas:idea_list" %}">{% trans "List of ideas" %}</a>
    <h1>
        {% if idea %}
            {% blocktrans trimmed with title=idea.translated_title %} 
                Change Idea "{{ title }}"
            {% endblocktrans %}
        {% else %}
            {% trans "Add Idea" %}
        {% endif %}
    </h1>
    {% crispy form %}

{% endblock %}
 
{% block js %}
    <script src="{% static 'site/js/inlines.js' %}"></script>
{% endblock %}

Chapter-07/website/src/project/templates/ideas/idea_handout_pdf.html
{% extends "base_pdf.html" %}
{% load i18n qr_code %}

{% block content %}
    <h1 class="h3">{% trans "Handout" %}</h1>
    <h2 class="h1">{{ idea.translated_title }}</h2>
    <img src="{{ idea.picture_large.url }}" alt="" class="img-responsive w-100" />
    <div class="my-3">{{ idea.translated_content|linebreaks|urlize }}</div>
    <p>
        {% for category in idea.categories.all %}
            <span class="badge badge-pill badge-info">{{ category.translated_title }}</span>
        {% endfor %}
    </p>
    <h4>{% trans "See more information online:" %}</h4>
    {% qr_from_text idea.get_url size=20 border=0 as svg_code %}
    <img alt="" src="data:image/svg+xml,{{ svg_code|urlencode }}" />
    <p class="mt-3 text-break">{{ idea.get_url }}</p>
{% endblock %}

Chapter-07/website/src/project/templates/ideas/idea_list.html
{% extends "base.html" %} 
{% load i18n utility_tags %}
 
{% block sidebar %}
  {% include "ideas/includes/filters.html" %}
{% endblock %}
 
{% block main %}
  <h1>{% trans "Ideas" %}</h1>
  {% if object_list %}
    {% for idea in object_list %}
      <a href="{{ idea.get_url_path }}" class="d-block my-3"> 
        <div class="card">
          <img src="{{ idea.picture_thumbnail.url }}" alt="" />
          <div class="card-body">
            <p class="card-text">{{ idea.translated_title }}</p>
          </div>
        </div> 
      </a>
    {% endfor %}
    {% include "misc/includes/pagination.html" %}
  {% else %}
    <p>{% trans "There are no ideas yet." %}</p>
  {% endif %}
  <a href="{% url 'ideas:add_idea' %}" class="btn btn-primary">{% trans "Add idea" %}</a>
{% endblock %}

Chapter-07/website/src/project/templates/ideas/idea_search.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}

{% block sidebar %}
    {% crispy form %}
{% endblock %}

{% block main %}
    <h1>{% trans "Search Results" %}</h1>
    {% if object_list %}
        {% for idea in object_list %}
            <a href="{{ idea.get_url_path }}" class="d-block my-3">
                <div class="card">
                  <img src="{{ idea.picture_thumbnail_url }}" alt="" />
                  <div class="card-body">
                    <p class="card-text">{{ idea.translated_title }}</p>
                  </div>
                </div>
            </a>
        {% endfor %}
        {% include "misc/includes/pagination.html" %}
    {% else %}
        <p>{% trans "No ideas found." %}</p>
    {% endif %}
{% endblock %}